map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

limit_req_zone $binary_remote_addr zone=general_api:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=expensive_api:10m rate=2r/s;
limit_conn_zone $binary_remote_addr zone=websocket_clients:10m;

server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root   /usr/share/nginx/html;
    index index.html;
    error_page   500 502 503 504  /50x.html;
    client_max_body_size 64k;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "DENY" always;

    include /etc/nginx/common_routes.conf;
}
