# Build step #1: react
FROM node:19-alpine as build-step
WORKDIR /reactf
ENV PATH /reactf/node_modules/.bin:$PATH
COPY . .
RUN yarn install
RUN yarn build

# Build step #2: nginx
FROM nginx:stable-alpine
COPY --from=build-step /reactf/build /usr/share/nginx/html
COPY --from=build-step /reactf/client.conf /etc/nginx/conf.d/default.conf